### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Alkimical** [descawed/re0box#7]
I get this error when trying to compitale unmodified script:

`error: failed to run custom build command for `re0box v0.4.1 (D:\Multimedia\Downloads\re0box-master\re0box-master)`

Caused by:
  process didn't exit successfully: `D:\Multimedia\Downloads\re0box-master\re0box-master\target\debug\build\re0box-6178c356ff98f0fb\build-script-build` (exit code: 101)
  --- stdout
  package.metadata does not exist
  "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe"
  "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\x64\\rc.exe"
  "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.26100.0\\x64\\rc.exe"

  --- stderr
  thread 'main' panicked at build.rs:3:19:
  called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...`

But actually theres rc.exe in my C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64

**Comment by descawed** [comment]
Looking at the [winresource source](https://github.com/BenjaminRi/winresource/blob/master/lib.rs#L749), it's not clear to me how you would get that "program not found" error. It should use the last path it prints out, and it checks that the path exists before printing it. Maybe it's a permission issue or a winresource bug?

Regardless, the fact that it's trying to use the x64 rc.exe means you're compiling for the wrong architecture. You should be using `cargo build --target=i686-pc-windows-msvc` to compile it as a 32-bit DLL (you may need to run `rustup target add i686-pc-windows-msvc` first to install the 32-bit Rust toolchain). You can try that and see if you have the same problem.

Worst case scenario, you can just delete build.rs and compile without it. All it does is set the version number and stuff in the DLL properties; it's not required for the mod to work.

**Comment by descawed** [comment]
I'm going to close this issue since I haven't heard from you in a bit, but feel free to reach out again if you're still having problems.
